### ISSUE TITLE
Fix watch list input 

### ISSUE THREAD

**Issue by robcxyz** [geometry-labs/icon-network-exporter#4]
Updated helm chart but new values not exposed in Argo.

**Comment by shinyfoil** [comment]
If new values aren't auto-populated, you'll need to override them with the CLI tool.

- Install CLI tool (https://argoproj.github.io/argo-cd/cli_installation/)

- Login with GH: `argocd login argocd.geometry-dev.net --sso --grpc-web`

- Add parameter(s): `argocd app set icon-monitor -p 'mainnet.main_watch_list=["ICON Pinas"]'`
